#include "Iron/Animation/Animation.h"
#include "Iron/Animation/Animator.h"
#include "Iron/Audio/AudioListener.h"
#include "Iron/Audio/AudioSource.h"
#include "Iron/Audio/AudioTrack.h"
#include "Iron/Core/Application.h"
#include "Iron/Core/Log.h"
#include "Iron/Core/Time.h"
#include "Iron/Core/Input.h"
#include "Iron/Physics/BoxCollider.h"
#include "Iron/Physics/RigidBody.h"
#include "Iron/Rendering/Screen.h"
#include "Iron/Rendering/Camera.h"
#include "Iron/Rendering/SpriteRenderer.h"
#include "Iron/Scene/Component.h"
#include "Iron/Scene/Object.h"
#include "Iron/Scene/Transformation.h"

// TODO: allow to include it independently
#include <glm/glm.hpp>